import datetime as dt
x = dt.datetime.now()
print(x)


y = dt.datetime.now()
print(y.year)
print(y.strftime("%A"))
print(y.strftime("%a"))

z = dt.datetime(2003, 5, 27, 13, 20, 21, 234565)
print(z)

print(z.strftime("%B"))
print(z.strftime("%b"))
print(z.strftime("%w"))
print(z.strftime("%d"))
print(z.strftime("%m"))
print(z.strftime("%y"))
print(z.strftime("%Y"))
print(z.strftime("%H"))
print(z.strftime("%I"))
print(z.strftime("%P"))
print(z.strftime("%p"))
print(z.strftime("%M"))
print(z.strftime("%S"))
print(z.strftime("%f"))
print(z.strftime("%j"))
print(z.strftime("%u"))
print(z.strftime("%U"))
print(z.strftime("%Z"))
print(z.strftime("%C"))
print(z.strftime("%x"))
print(z.strftime("%"))